package project2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CreateAccount extends javax.swing.JFrame {

    static public String AccountNo;
    String EmailId;
    boolean Panerror, Emailerror, Adharerror = false;

    // Generating Unique Account No using Date Time Object
    LocalDateTime myDateObj = LocalDateTime.now();
    DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("ddMMyyHHmmss");
    public String formattedDate = myDateObj.format(myFormatObj);

    public Connection connect;

    public CreateAccount() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        MobileNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanNumber = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AdharNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CheckButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        Gender = new javax.swing.JComboBox<>();
        AccountType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ErrorMessage = new javax.swing.JLabel();
        AdharError = new javax.swing.JLabel();
        EmailError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5));

        Heading.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 0, 255));
        Heading.setText("Registration Form");

        BackButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(153, 153, 153));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-back-arrow-30.png"))); // NOI18N
        BackButton.setText("Go Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        LastName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N

        MobileNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N

        jLabel5.setText("Mobile Number");

        jLabel6.setText("Pan Number");

        PanNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        PanNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PanNumberFocusLost(evt);
            }
        });

        Email.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });

        jLabel7.setText("Email ");

        AdharNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        AdharNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdharNumberFocusLost(evt);
            }
        });

        jLabel8.setText("Aadhar Number");

        jLabel9.setText("Gender");

        jLabel10.setText("Account Type");

        CheckButton.setBackground(new java.awt.Color(0, 0, 255));
        CheckButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        CheckButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-search-client-30.png"))); // NOI18N
        CheckButton.setText("Create Account");
        CheckButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-circled-user-male-skin-type-1-2-100 (2).png"))); // NOI18N

        CloseButton.setBackground(new java.awt.Color(255, 0, 0));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/Images/icons8-close-window-30.png"))); // NOI18N
        CloseButton.setBorder(null);
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        AccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Current" }));

        Address.setColumns(20);
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        jLabel2.setText("Address");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        ErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        ErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorMessage.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CheckButton)
                        .addGap(345, 345, 345))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Gender, 0, 257, Short.MAX_VALUE)
                                            .addComponent(MobileNumber)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Email)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(EmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel3)
                                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(142, 142, 142)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(LastName)
                                        .addComponent(PanNumber)
                                        .addComponent(AdharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(AdharError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel10)
                                        .addComponent(AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(ErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(34, 34, 34))))
                        .addGap(125, 125, 125))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BackButton)
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(475, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Heading)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstName)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ErrorMessage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(EmailError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(AdharError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(CheckButton)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        // TODO add your handling code here:

        String MobileNo = MobileNumber.getText();
        String PanNo = PanNumber.getText();
        EmailId = Email.getText();
        String AdharNo = AdharNumber.getText();
        String Fname = FirstName.getText();
        String Lname = LastName.getText();
        String Adress = Address.getText();
        String CGender = Gender.getSelectedItem().toString();
        String AcType = AccountType.getSelectedItem().toString();
        boolean Checker = true;

        if (!"".equals(Fname)) {
            Checker = true;
            FirstName.setBackground(Color.GREEN);

            if (!"".equals(Lname)) {
                Checker = true;
                LastName.setBackground(Color.GREEN);

                if (MobileNo != "" && MobileNo.matches("^[0-9]*$") && MobileNo.length() == 10) {
                    Checker = true;
                    MobileNumber.setBackground(Color.GREEN);

                    if (PanNo.length() == 10) {
                        Checker = true;
                        PanNumber.setBackground(Color.GREEN);

                        if (EmailId.matches("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$")) {
                            Checker = true;
                            Email.setBackground(Color.GREEN);

                            if (AdharNo.matches("^[0-9]*$") && AdharNo.length() == 12) {
                                Checker = true;
                                AdharNumber.setBackground(Color.GREEN);

                                if (!"".equals(Adress)) {
                                    Checker = true;
                                    Address.setBackground(Color.GREEN);

                                    //  Database Connection and queries
                                    if (Checker == true) {

                                        if (Panerror == false && Adharerror == false && Emailerror == false) {

                                            AccountNo = formattedDate;

                                            try {

                                                Class.forName("com.mysql.jdbc.Driver");
                                                connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/deccanbank","root","");
                                                String query = "Insert into customer_detail(First_Name, Last_Name, Gender, Mobile_Number, Pan_Number, Account_Number, Account_Type, Adhar_Number, Balance, Email, Address, Account_Status) Values ('" + Fname + "', '" + Lname + "', '" + CGender + "', '" + MobileNo + "', '" + PanNo + "', '" + AccountNo + "', '" + AcType + "', '" + AdharNo + "', 0.0, '" + EmailId + "', '" + Adress + "', 'Active')";
                                                PreparedStatement pst = connect.prepareStatement(query);
                                                pst.execute();
                                            } catch (Exception e) {

                                                System.out.print(e);
                                            }

                                            MailVerification Mv = new MailVerification();
                                            setVisible(false);
                                            dispose();
                                            Mv.setVisible(true);
                                            FirstName.setText("");
                                            LastName.setText("");
                                            MobileNumber.setText("");
                                            Email.setText("");
                                            PanNumber.setText("");
                                            AdharNumber.setText("");
                                        }

                                    } else {
                                        JOptionPane.showMessageDialog(null, "Please Correct your details");
                                    }

                                } else {

                                    Checker = false;
                                    Address.setBackground(new Color(246, 53, 40));
                                }
                            } else {
                                Checker = false;
                                AdharNumber.setBackground(new Color(246, 53, 40));
                            }

                        } else {
                            Checker = false;
                            Email.setBackground(new Color(246, 53, 40));

                        }

                    } else {
                        Checker = false;
                        PanNumber.setBackground(new Color(246, 53, 40));
                    }
                } else {
                    Checker = false;
                    MobileNumber.setBackground(new Color(246, 53, 40));
                }
            } else {
                Checker = false;
                LastName.setBackground(new Color(246, 53, 40));
            }
        } else {
            Checker = false;
            FirstName.setBackground(new Color(246, 53, 40));
            System.out.print("error2");
        }


    }//GEN-LAST:event_CheckButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        setVisible(false);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void PanNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanNumberFocusLost

        try {

            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/deccanbank","root","");
            String query = "Select * from customer_detail where Pan_Number=?";
            PreparedStatement pst = connect.prepareStatement(query);
            pst.setString(1, PanNumber.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Panerror = true;
                ErrorMessage.setText("* Pan Number Already Exists");
                ErrorMessage.setForeground(Color.red);
                PanNumber.setBackground(Color.red);
            } else {
                Panerror = false;
                ErrorMessage.setText("");
                ErrorMessage.setForeground(Color.green);
                PanNumber.setBackground(Color.white);
            }
        } catch (Exception e) {

            System.out.print("i run");

        }
    }//GEN-LAST:event_PanNumberFocusLost

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
        try {

            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/deccanbank","root","");
            String query = "Select * from customer_detail where Email=?";
            PreparedStatement pst = connect.prepareStatement(query);
            pst.setString(1, Email.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Emailerror = true;
                EmailError.setText("* Email Address Already Exists");
                EmailError.setForeground(Color.red);
                Email.setBackground(Color.red);
            } else {
                Emailerror = false;
                EmailError.setText("");
                EmailError.setForeground(Color.green);
                Email.setBackground(Color.white);
            }
        } catch (Exception e) {

            System.out.print("i run");

        }
    }//GEN-LAST:event_EmailFocusLost

    private void AdharNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdharNumberFocusLost
        // TODO add your handling code here:
        try {

            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/deccanbank","root","");
            String query = "Select * from customer_detail where Adhar_Number=?";
            PreparedStatement pst = connect.prepareStatement(query);
            pst.setString(1, AdharNumber.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Adharerror = true;
                AdharError.setText("* Aadhar Number Already Exists");
                AdharError.setForeground(Color.red);
                AdharNumber.setBackground(Color.red);
            } else {
                Adharerror = false;
                AdharError.setText("");
                AdharError.setForeground(Color.green);
                AdharNumber.setBackground(Color.white);
            }
        } catch (Exception e) {

            System.out.print("i run");

        }

    }//GEN-LAST:event_AdharNumberFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountType;
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel AdharError;
    private javax.swing.JTextField AdharNumber;
    private javax.swing.JLabel BackButton;
    private javax.swing.JButton CheckButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailError;
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JTextField FirstName;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JLabel Heading;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MobileNumber;
    private javax.swing.JTextField PanNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
